=== PaulTheStrong/EpamXmlTask/src/main/resources/xml/deposit-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/deposits"
        xmlns:tns="http://www.example.com/deposits"
        elementFormDefault="qualified">
    <element name="deposit"
             type="tns:Deposit"/>
    <element name="term-deposit"
             type="tns:TermDeposit"
             substitutionGroup="tns:deposit" />
    <element name="deposits">
        <complexType>
            <sequence>
               <element ref="tns:deposit" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Deposit">
        <sequence>
            <element name="bank-name" type="string"/>
            <element name="amount" type="double"/>
            <element name="profitability">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0" />
                        <maxInclusive value="100" />
                    </restriction>
                </simpleType>
            </element>
            <element name="info" type="string"/>
            <element name="currency">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="BYN" />
                        <enumeration value="USD" />
                        <enumeration value="EUR" />
                        <enumeration value="UAH" />
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="country" default="Belarus"/>
        <attribute name="account-id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[A-Z]{2}\d{7}" />
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="TermDeposit">
        <complexContent>
            <extension base="tns:Deposit">
                <sequence>
                    <element name="start-date" type="date" />
                    <element name="end-date" type="date"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== PaulTheStrong/EpamXmlTask/src/main/resources/xml/deposits.xml
<deposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.example.com/deposits"
            xsi:schemaLocation="http://www.example.com/deposits deposit-schema.xsd">
    <deposit account-id="AD7654321">
        <bank-name>BSB Bank</bank-name>
        <amount>1000</amount>
        <profitability>5</profitability>
        <info>First deposit</info>
        <currency>BYN</currency>
    </deposit>
    <deposit account-id="PM3221337" country="USA">
        <bank-name>Cool American Bank</bank-name>
        <amount>40000</amount>
        <profitability>12.5</profitability>
        <info />
        <currency>USD</currency>
    </deposit>
    <term-deposit account-id="AB2312133" country="USA"> <!-- Incorrect ID Проверить, как будет парситься -->
        <bank-name>Less American Bank</bank-name>
        <amount>10000</amount>
        <profitability>5.3</profitability>
        <info>The profitability less than in Cool American Bank</info>
        <currency>EUR</currency>
        <start-date>2021-06-12</start-date>
        <end-date>2021-09-12</end-date>
    </term-deposit>
    <term-deposit account-id="MT3211233">
        <bank-name>Dungeon bank</bank-name>
        <amount>300</amount>
        <profitability>100</profitability>
        <info>Three hundred bucks bank deposit</info>
        <currency>USD</currency>
        <start-date>2001-01-01</start-date>
        <end-date>2021-01-01</end-date>
    </term-deposit>
</deposits>
